/* generated by Svelte v4.2.0 */
import {
	create_ssr_component,
	each,
	escape,
	validate_component
} from "svelte/internal";

import { onMount } from "svelte";
import Nav from "../lib/Nav.js";

const Component = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { data } = $$props;

	onMount(async () => {
		console.log('hello');
	});

	if ($$props.data === void 0 && $$bindings.data && data !== void 0) $$bindings.data(data);

	return `${validate_component(Nav, "Nav").$$render($$result, {}, {}, {})} <div class="container mt-5">${each(data.posts, item => {
		return `${item.page == 'index'
		? `<section class="p-3"><h1>${escape(item.title)}</h1> ${item.body} </section>`
		: ``}`;
	})}</div>`;
});

export default Component;