/* generated by Svelte v4.2.0 */
import { create_ssr_component } from "svelte/internal";

const Component = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<nav><a href="/">Home</a> <a href="/about.html">About</a></nav>`;
});

export default Component;