/* generated by Svelte v4.2.0 */
import { create_ssr_component, each, escape } from "svelte/internal";

const css = {
	code: "nav.svelte-7u46t3.svelte-7u46t3{background-color:#f8f9fa;padding:10px;padding-bottom:12px;border-bottom:1px solid #DDD}nav.svelte-7u46t3 a.svelte-7u46t3{margin-left:10px;text-decoration:none}",
	map: "{\"version\":3,\"sources\":[\"\"],\"sourcesContent\":[\"<script>\\n    export let data;\\n</script>\\n\\n<nav>\\n    {#each data.pages as page}\\n    <a href=\\\"./{page.slug}.html\\\">{page.title}</a>\\n    {/each}\\n</nav>\\n\\n\\n<style>\\n    nav {\\n        background-color: #f8f9fa;\\n        padding: 10px;\\n        padding-bottom: 12px;\\n        border-bottom: 1px solid #DDD;\\n    }\\n\\n    nav a {\\n        margin-left: 10px;\\n        text-decoration: none;\\n    }\\n</style>\\n\\n\"],\"names\":[],\"mappings\":\"AAYI,+BAAI,CACA,gBAAgB,CAAE,OAAO,CACzB,OAAO,CAAE,IAAI,CACb,cAAc,CAAE,IAAI,CACpB,aAAa,CAAE,GAAG,CAAC,KAAK,CAAC,IAC7B,CAEA,iBAAG,CAAC,eAAE,CACF,WAAW,CAAE,IAAI,CACjB,eAAe,CAAE,IACrB\"}"
};

const Component = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { data } = $$props;
	if ($$props.data === void 0 && $$bindings.data && data !== void 0) $$bindings.data(data);
	$$result.css.add(css);

	return `<nav class="svelte-7u46t3">${each(data.pages, page => {
		return `<a href="${"./" + escape(page.slug, true) + ".html"}" class="svelte-7u46t3">${escape(page.title)}</a>`;
	})} </nav>`;
});

export default Component;