/* generated by Svelte v4.2.0 */
import { create_ssr_component, escape } from "svelte/internal";

const Component = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { item } = $$props;
	if ($$props.item === void 0 && $$bindings.item && item !== void 0) $$bindings.item(item);
	return `<section class="p-3"><h1>${escape(item.title)}</h1> ${item.body}</section>`;
});

export default Component;